add: Initial repo setup
RealDevSquad/feature-flag-frontend pull request #2
Opened 2024-11-04 06:00 UTC by MehulKChaudhari

Date: 4/11/2024

Developer Name: @MehulKChaudhari 

---

## Issue Ticket Number

## Description

This PR will add basic repo setup for frontend of feature-flag, (React Typescript Vite)

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-11-04 06:03 UTC, MehulKChaudhari commented
Note: Tests setup will come in subsequent PR, It would have increased the number of files changes and the scope of this PR that's why keeping it separate.

2024-11-04 19:40 UTC, prakashchoudhary07 requested changes

2024-11-04 19:40 UTC, prakashchoudhary07 commented on index.html
> +    <title>Vite + React + TS</title>
Please change the title?

2024-11-04 19:40 UTC, prakashchoudhary07 commented on pnpm-lock.yaml
Are we sure we are going to use pnpm?
why not npm?

2024-11-04 19:54 UTC, MehulKChaudhari commented on index.html
> +    <title>Vite + React + TS</title>
Oops, Changed. 

Thanks for noticing :)

2024-11-04 19:55 UTC, MehulKChaudhari commented on pnpm-lock.yaml
Yes, Pnpm has better features than npm. 

Its fast, Efficient Disk Space Usage, Better Handling of Peer Dependencies etc

2024-11-05 20:45 UTC, prakashchoudhary07 submitted a review, later dismissed

2024-11-06 02:25 UTC, prakashchoudhary07 commented on .github/workflows/ci.yml
> +name: CI
Please add a time out

2024-11-06 02:26 UTC, prakashchoudhary07 commented on .github/workflows/ci.yml
> +          node-version: 18
Please use latest node version

2024-11-06 02:27 UTC, prakashchoudhary07 approved these changes

2024-11-06 02:28 UTC, merged

2024-11-06 02:29 UTC, prakashchoudhary07 commented on package.json
> +    "test:watch": "vitest --watch"
Please add coverage report command